### ISSUE TITLE
"press any key" does not actually work

### ISSUE THREAD

**Issue by Pharb** [michowski/tetris-light#1] opened 2016-07-24 12:12 UTC
**Bug:** Pressing e.g. arrow keys, ESC or Return does not start the game.

**Cause:** The user has to press a key that produces a "character value" due to the use of the "keypress" event in https://github.com/michowski/tetris-light/blob/master/index-source.html#L268

This behavior of the "keypress" event is specified here: https://www.w3.org/TR/uievents/#event-type-keypress

**Fix:** Extend the existing "keydown" handler to also start the game.

**Comment by liftoff** [comment] 2016-07-25 18:28
I just noticed this issue and I believe my PR #7 (which was just merged) fixes it.  Can you grab the latest code and test?

"Works for me" :smile: 

BTW:  Test the index-source.html as that's the only file I updated in my PR.

**Comment by michowski** [comment] 2016-07-25 18:31
Indeed, it does work. Thank you. The only problem is that with the current state pressing "any key" instantly after loosing is way too common. I will make a general update in my free time to keep **index.html** up-to-date ;) .

**Closed as completed by michowski** 2016-07-25 18:31 UTC

**Comment by liftoff** [comment] 2016-07-25 18:33
Oh that's a good point.  Better move that logic to the keyup event then.  Should be a quick fix =)

**Comment by michowski** [comment] 2016-07-25 18:37
From what I remember, **keyup** is firing instantly too. The problem is, generally, that the last moves are usually the most exciting ones :) .

**Comment by liftoff** [comment] 2016-07-25 18:42
Oh, that might be because of keyrepeat.  To fix that you can check the event.repeat attribute...

```
if (event.repeat) { event.preventDefault(); return false; }
```

**Comment by michowski** [comment] 2016-07-25 18:44
That's a nice idea! I will try it for sure :) .
